static const unsigned char WordCheck[8] =
{
    242,53,162,2,214,144,70,39
};
#define WORD_FILE_SIZE 1677294
#define ROOT_NODE_LOC 0
#define BITS_CHILD_PATT_INDEX 14
#define BITS_CHILD_MAP_INDEX  18
#define SHIFT_CHILD_MAP_INDEX BITS_CHILD_PATT_INDEX
#define SHIFT_WORD_ENDING_BIT (SHIFT_CHILD_MAP_INDEX + BITS_CHILD_MAP_INDEX)
#define CHARSET_SIZE 49
